*Numpy*

In [8]:
import numpy as np

# 1d Array --
arr1 = np.array([1, 2, 3, 4, 5])

# print(arr1.ndim, end=" ")

# 2d Array --
arr2 = np.array([[1, 3, 6, 9], [2, 4, 6, 8]])

print(arr2)

[[1 3 6 9]
 [2 4 6 8]]


*Array Attibutes*

In [12]:
# Dimenstion
print(arr1.ndim)

# shape
print(arr1.shape)
print(arr2.shape)

# D-Type
print(arr1.dtype)

1
(5,)
(2, 4)
int64


*NumPy Data Type*

In [16]:
arr = np.array([1, 2, 3])

# upcusting int to float
print(arr.dtype)

# upcasting int to float

arr1 = np.array([1, 2 , 2.5])

print(arr1.dtype)

int64
float64


*Select a data type for an array*

In [19]:
arr = np.array([1, 2, 4, 6], dtype=np.int8)
print(arr)
print(arr.dtype)
arr = arr.astype(np.int16)

[1 2 4 6]
int8


In [25]:
matrix = np.array([[4, 5, 8], [6, 7, 2]])

print(matrix.dtype)
print(matrix.shape)

int64
(2, 3)


In [28]:
sets = {4, 7, 8, 9, 8}

arr = np.array(list(sets)%%!)
print(arr)

[8 9 4 7]


*Random Values*

In [60]:
arr = np.random.rand(10, 5)
print(arr.dtype)
print(arr.shape)
print(arr.size)

float64
(10, 5)
50


In [73]:
# np.random.randint(start, end, shape)

arr = np.random.randint(10, 50, (5, 5))

print(arr)

[[49 18 18 32 23]
 [38 20 48 33 49]
 [33 15 45 47 36]
 [48 27 24 35 45]
 [33 44 49 43 47]]


In [74]:
# np.random.uniform(start, end, shape)

arr = np.random.uniform(10, 50, (5, 5))

print(arr)

[[13.4552551  46.07429353 25.11730921 25.18544671 12.1248506 ]
 [15.82708815 39.47332978 36.89259193 39.41583034 14.2295992 ]
 [31.03175294 38.48161712 18.2707575  48.92087317 28.29207907]
 [41.49098206 13.6416775  47.21495638 39.37206188 23.13541643]
 [28.31739852 29.13985358 38.13824676 19.84700379 47.05038123]]


*Arange Function*

In [80]:
# arange accept(where start, where end, and step) --- simpiler to loop range function
arr = np.arange(50, 101, 5)

print(arr)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [90]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]
